[package]
name = "make_tests"
version = "0.1.0"
authors = ["Gavin Peacock <gpeacock@adobe.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
rust-version = "1.58.0"

[dependencies]
anyhow = "1.0"
c2pa = { path="../sdk", features = ["file_io"] }
env_logger = "0.9"
log = "0.4" 
tempfile = "3.3"
image = "0.23.10"
nom = "7.1.1"
regex = "1.5.6"
serde = "1.0.137"
serde_json = "1.0.81"
twoway = "0.2.2"


