[package]
name = "c2pa_macros"
version.workspace = true
authors = ["Gavin Peacock <gpeacock@adobe.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.85.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40" 
syn = { version = "2.0.82" }
